<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

//HOUSE

$houseID = '';
if(isset($_GET['houseID'])){
    $houseID = $_GET['houseID'];
}

$houseName = '';
if(isset($_GET['houseName'])){
    $houseName = $_GET['houseName'];
}

//HOUSEROLE

$houseRoleID = '';
if(isset($_GET['houseRoleID'])){
    $houseRoleID = $_GET['houseRoleID'];
}

//ACCOUNT
$accountID = '';
if(isset($_GET['accountID'])){
    $accountID = $_GET['accountID'];
}

$accountName = '';
if(isset($_GET['accountName'])){
    $accountName = $_GET['accountName'];
}

$email = '';
if(isset($_GET['email'])){
    $email = $_GET['email'];
}

$age = 0;
if(isset($_GET['age'])){
    $age = (INT)$_GET['age'];
}

$accountHouseID = '';
if(isset($_GET['accountHouseID'])){
    $accountHouseID = $_GET['accountHouseID'];
}

$accountHouseRoleID = '';
if(isset($_GET['accountHouseRoleID'])){
    $accountHouseRoleID = $_GET['accountHouseRoleID'];
}


//Fetch data from database
$houseArray = $database->selectAllHouses($houseID, $houseName, $creatorCount, $fanCount);
$accountArray = $database->selectAllAccounts($accountID, $accountName, $email, $age, $accountHouseID, $accountHouseRoleID);
?>

<html>
<link rel="stylesheet" href="css/styles.css">
<head>
    <title>TrueWestPost</title>
</head>

<body>
<br>
<h1>Houses</h1>



<!-- Add House -->
<h2>Add House: </h2>
<form method="post" action="addHouse.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- HouseName textbox -->
    <div>
        <label for="newHouseName">House Name:</label>
        <input id="newHouseName" name="houseName" type="text" maxlength="20">
    </div>
    <br>
    <!-- Submit button -->
    <div>
        <button type="submit">
            Add House
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete House -->
<h2>Delete House: </h2>
<form method="post" action="delHouse.php">
    <!-- ID textbox -->
    <div>
        <label for="del_house">ID:</label>
        <input id="del_house" name="id" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete House
        </button>
    </div>
</form>
<br>
<hr>


<!-- Update House -->
<h2>Update House: </h2>
<form method="post" action="updateWindowHouse.php">
    <div>
        <label for="updateID">ID: </label>
        <input id="updateID" name = "id" type="number" mind = "0">
    </div>
    <br>
    <div>
        <button type="submit">
            Update
        </button>
    </div>
</form>
<br>
<hr>

<a href="index.php">
    go back
</a>


<!-- Search result -->
<h2>Houses:</h2>
<div class="array">
    <div class="array">
        <table>
            <tr>
                <th>ID</th>
                <th>HouseName</th>
                <th>CreatorCount</th>
                <th>FanCount</th>
            </tr>
            <?php foreach ($houseArray as $Houses) : ?>
                <tr>
                <td><?php echo $Houses['HOUSEID']; ?> </td>
                <td><?php echo $Houses['HOUSENAME']; ?> </td>
                <td><?php echo $Houses['CREATORCOUNT']; ?> </td>
                <td><?php echo $Houses['FANCOUNT']; ?> </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
